
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>login | Cherry Tree Soft

    </title>
</head>
<body>
    <div class="row mt-4 justify-content-center"> 
<div class="col-sm-10 col-md-10 col-lg-10">
    <h1 class="text-center">login | <span class="text-danger">Cherry Tree Soft</span></h1>

</div>
    </div>
    <div class="row container justify-content-center mt-3">
        <div class="col col-sm-8 col-md-8 col-lg-8">
            <div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">
    <svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="Library/icons/bootstrap-icons.svg#person-circle-fill"/>
</svg>
  </span>
  <input type="text" class="form-control" placeholder="Usuario" aria-label="Usuario" aria-describedby="basic-addon1">
</div>
        </div>
    </div>
    </div>
    <div class="row container justify-content-center mt-3">
        <div class="col col-sm-8 col-md-8 col-lg-8">
            <div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">
    <svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="Library/icons/bootstrap-icons.svg#lock-fill"/>
</svg>
  </span>
  <input type="text" class="form-control" placeholder="password" aria-label="password" aria-describedby="basic-addon1">
</div>
        </div>
    </div>
    <div class="row mt-1">
        <input type="submit" value="ingresar" class="btn btn-se btn-sucess">
    </div>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>